spring.application.name=ai-support-assistant

server.port=8080
spring.web.resources.static-locations=file:./frontend/dist/

# GigaChat
gigachat.auth.url=https://ngw.devices.sberbank.ru:9443/api/v2/oauth
gigachat.api.url=https://api.giga.chat/v1/chat/completions
gigachat.auth.key=MDFhMDk0YWMtOWZjOC03ZGY5LTgxMWMtNTEzYWE5ZjUyOGMxOjc2Mzg5YWI3LWM0MWItNGU3NC1iZjI0LTQyZDA1ZDBiOWVjMQ==
gigachat.scope=GIGACHAT_API_PERS
gigachat.model=GigaChat-2-Max
